ALTER TABLE "AiGenerationAttempt" ADD COLUMN "usageState" TEXT CHECK ("usageState" IS NULL OR "usageState" IN ('not_applicable', 'pending', 'captured', 'unavailable'));
ALTER TABLE "AiGenerationAttempt" ADD COLUMN "costState" TEXT CHECK ("costState" IS NULL OR "costState" IN ('not_applicable', 'pending', 'estimated', 'unknown'));
ALTER TABLE "AiGenerationAttempt" ADD COLUMN "providerSnapshot" TEXT;
ALTER TABLE "AiGenerationAttempt" ADD COLUMN "requestedModel" TEXT;
ALTER TABLE "AiGenerationAttempt" ADD COLUMN "effectiveModel" TEXT;
ALTER TABLE "AiGenerationAttempt" ADD COLUMN "effectiveModelSource" TEXT CHECK ("effectiveModelSource" IS NULL OR "effectiveModelSource" IN ('provider', 'requested_fallback'));
ALTER TABLE "AiGenerationAttempt" ADD COLUMN "inputTokens" BIGINT CHECK ("inputTokens" IS NULL OR "inputTokens" >= 0);
ALTER TABLE "AiGenerationAttempt" ADD COLUMN "inputTokensNoCache" BIGINT CHECK ("inputTokensNoCache" IS NULL OR "inputTokensNoCache" >= 0);
ALTER TABLE "AiGenerationAttempt" ADD COLUMN "inputTokensCacheRead" BIGINT CHECK ("inputTokensCacheRead" IS NULL OR "inputTokensCacheRead" >= 0);
ALTER TABLE "AiGenerationAttempt" ADD COLUMN "inputTokensCacheWrite" BIGINT CHECK ("inputTokensCacheWrite" IS NULL OR "inputTokensCacheWrite" >= 0);
ALTER TABLE "AiGenerationAttempt" ADD COLUMN "outputTokens" BIGINT CHECK ("outputTokens" IS NULL OR "outputTokens" >= 0);
ALTER TABLE "AiGenerationAttempt" ADD COLUMN "outputTextTokens" BIGINT CHECK ("outputTextTokens" IS NULL OR "outputTextTokens" >= 0);
ALTER TABLE "AiGenerationAttempt" ADD COLUMN "outputReasoningTokens" BIGINT CHECK ("outputReasoningTokens" IS NULL OR "outputReasoningTokens" >= 0);
ALTER TABLE "AiGenerationAttempt" ADD COLUMN "totalTokens" BIGINT CHECK ("totalTokens" IS NULL OR "totalTokens" >= 0);
ALTER TABLE "AiGenerationAttempt" ADD COLUMN "usageCapturedAt" DATETIME;
ALTER TABLE "AiGenerationAttempt" ADD COLUMN "usageUnavailableReason" TEXT;
ALTER TABLE "AiGenerationAttempt" ADD COLUMN "pricingVersion" TEXT;
ALTER TABLE "AiGenerationAttempt" ADD COLUMN "pricingCurrency" TEXT;
ALTER TABLE "AiGenerationAttempt" ADD COLUMN "inputRateNanoUsdPerToken" BIGINT CHECK ("inputRateNanoUsdPerToken" IS NULL OR "inputRateNanoUsdPerToken" >= 0);
ALTER TABLE "AiGenerationAttempt" ADD COLUMN "cacheReadRateNanoUsdPerToken" BIGINT CHECK ("cacheReadRateNanoUsdPerToken" IS NULL OR "cacheReadRateNanoUsdPerToken" >= 0);
ALTER TABLE "AiGenerationAttempt" ADD COLUMN "cacheWriteRateNanoUsdPerToken" BIGINT CHECK ("cacheWriteRateNanoUsdPerToken" IS NULL OR "cacheWriteRateNanoUsdPerToken" >= 0);
ALTER TABLE "AiGenerationAttempt" ADD COLUMN "outputRateNanoUsdPerToken" BIGINT CHECK ("outputRateNanoUsdPerToken" IS NULL OR "outputRateNanoUsdPerToken" >= 0);
ALTER TABLE "AiGenerationAttempt" ADD COLUMN "estimatedCostNanoUsd" BIGINT CHECK ("estimatedCostNanoUsd" IS NULL OR ("estimatedCostNanoUsd" >= 0 AND "costState" = 'estimated' AND "usageState" = 'captured'));
ALTER TABLE "AiGenerationAttempt" ADD COLUMN "costUnavailableReason" TEXT;
